# Your Wi-Fi SSID and password
wifi_ssid: "test_ssid"
wifi_password: "test_password"
# Your Home Assistant API encryption key
api_encryption_key: "test_api_encryption_key"
# Your Over-The-Air (OTA) password
ota_password: "test_ota_password"
# Your Wi-Fi AP password
wifi_ap_password: "test_wifi_ap_password"